name: voice_diary
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1
  flutter: 3.29.0

dependencies:
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  cloud_firestore: ^5.6.5
  
  flutter:
    sdk: flutter

  # Internal packages
  
  core:
    path: ./packages/core

  firebase_login:
    path: ./packages/firebase_login

  domain:
    path: ./packages/domain

  # External packages

  flutter_bloc: ^9.1.0
  go_router: ^14.8.1
  phosphor_flutter: ^2.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_core: ^3.12.1
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
