// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'local/record/models/record_local_entity.dart';
import 'local/user_preferences/models/user_preferences_local_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 3059967523835835008),
      name: 'RecordLocalEntity',
      lastPropertyId: const obx_int.IdUid(5, 7571024112495273133),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4526747477504274627),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3628661722777011639),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4738870787765072502),
            name: 'date',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6246985951761302473),
            name: 'path',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7571024112495273133),
            name: 'tags',
            type: 30,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 276343024614356600),
      name: 'UserPreferencesLocalEntity',
      lastPropertyId: const obx_int.IdUid(2, 590671320434861678),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7996433342778773472),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 590671320434861678),
            name: 'selectedLocale',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 276343024614356600),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    RecordLocalEntity: obx_int.EntityDefinition<RecordLocalEntity>(
        model: _entities[0],
        toOneRelations: (RecordLocalEntity object) => [],
        toManyRelations: (RecordLocalEntity object) => {},
        getId: (RecordLocalEntity object) => object.id,
        setId: (RecordLocalEntity object, int id) {
          object.id = id;
        },
        objectToFB: (RecordLocalEntity object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final pathOffset = fbb.writeString(object.path);
          final tagsOffset = fbb.writeList(
              object.tags.map(fbb.writeString).toList(growable: false));
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addInt64(2, object.date.millisecondsSinceEpoch);
          fbb.addOffset(3, pathOffset);
          fbb.addOffset(4, tagsOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final dateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final pathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final tagsParam = const fb.ListReader<String>(
                  fb.StringReader(asciiOptimization: true),
                  lazy: false)
              .vTableGet(buffer, rootOffset, 12, []);
          final object = RecordLocalEntity(
              id: idParam,
              title: titleParam,
              date: dateParam,
              path: pathParam,
              tags: tagsParam);

          return object;
        }),
    UserPreferencesLocalEntity:
        obx_int.EntityDefinition<UserPreferencesLocalEntity>(
            model: _entities[1],
            toOneRelations: (UserPreferencesLocalEntity object) => [],
            toManyRelations: (UserPreferencesLocalEntity object) => {},
            getId: (UserPreferencesLocalEntity object) => object.id,
            setId: (UserPreferencesLocalEntity object, int id) {
              object.id = id;
            },
            objectToFB: (UserPreferencesLocalEntity object, fb.Builder fbb) {
              final selectedLocaleOffset =
                  fbb.writeString(object.selectedLocale);
              fbb.startTable(3);
              fbb.addInt64(0, object.id);
              fbb.addOffset(1, selectedLocaleOffset);
              fbb.finish(fbb.endTable());
              return object.id;
            },
            objectFromFB: (obx.Store store, ByteData fbData) {
              final buffer = fb.BufferContext(fbData);
              final rootOffset = buffer.derefObject(0);
              final idParam =
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
              final selectedLocaleParam =
                  const fb.StringReader(asciiOptimization: true)
                      .vTableGet(buffer, rootOffset, 6, '');
              final object = UserPreferencesLocalEntity(
                  id: idParam, selectedLocale: selectedLocaleParam);

              return object;
            })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [RecordLocalEntity] entity fields to define ObjectBox queries.
class RecordLocalEntity_ {
  /// See [RecordLocalEntity.id].
  static final id =
      obx.QueryIntegerProperty<RecordLocalEntity>(_entities[0].properties[0]);

  /// See [RecordLocalEntity.title].
  static final title =
      obx.QueryStringProperty<RecordLocalEntity>(_entities[0].properties[1]);

  /// See [RecordLocalEntity.date].
  static final date =
      obx.QueryDateProperty<RecordLocalEntity>(_entities[0].properties[2]);

  /// See [RecordLocalEntity.path].
  static final path =
      obx.QueryStringProperty<RecordLocalEntity>(_entities[0].properties[3]);

  /// See [RecordLocalEntity.tags].
  static final tags = obx.QueryStringVectorProperty<RecordLocalEntity>(
      _entities[0].properties[4]);
}

/// [UserPreferencesLocalEntity] entity fields to define ObjectBox queries.
class UserPreferencesLocalEntity_ {
  /// See [UserPreferencesLocalEntity.id].
  static final id = obx.QueryIntegerProperty<UserPreferencesLocalEntity>(
      _entities[1].properties[0]);

  /// See [UserPreferencesLocalEntity.selectedLocale].
  static final selectedLocale =
      obx.QueryStringProperty<UserPreferencesLocalEntity>(
          _entities[1].properties[1]);
}
