name: domain
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.1
  flutter: 3.29.0

dependencies:
  flutter:
    sdk: flutter

  # Internal packages

  core:
    path: ../core

  remote:
    path: ../remote

  local:
    path: ../local

  result:
    path: ../result

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: false