name: remote
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: 3.29.0

dependencies:
  flutter:
    sdk: flutter

  # Internal packages

  core:
    path: ../core

  # External packages
  
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: false